name: Sync to Hugging Face Space

# This tells GitHub to run the script every time you push to the 'main' branch
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # This step uses your secret token to push the code to Hugging Face
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://debayanpaul64:$HF_TOKEN@huggingface.co/spaces/debayanpaul64/ai-ats-backend main
